### ISSUE TITLE
Consider use FetchContent_Declare

### ISSUE THREAD

**Issue by FirstLoveLife** [Morwenn/tight_pair#5]
cmake has https://cmake.org/cmake/help/v3.11/module/FetchContent.html since 3.11 and is a good alternative of https://github.com/Morwenn/tight_pair/blob/master/tests/CMakeLists.txt#L1

(I tried modify myself, but fail: `Unknown CMake command "catch_discover_tests".` and I'm unfamiliar with cmake)

**Comment by Morwenn** [comment]
I intended to try it later. Considering the requirements of this project, pushing the requirements to use Xenial in the CI and CMake 3.11 shouldn't be a problem. I'll have a look at it soon enough.
