### ISSUE TITLE
What's the point of catch_discover_tests(tight_pair-testsuite EXTRA_ARGS --rng-seed ${RNG_SEED})

### ISSUE THREAD

**Issue by FirstLoveLife** [Morwenn/tight_pair#8]
https://github.com/Morwenn/tight_pair/commit/23d3681d5f22189a849f84f9b24f291352461fd8#diff-3dea97423f83302e647a3bab62bf1157R87

I cannot find anywhere you use the generated random numbers(iiuc) in.

**Comment by Morwenn** [comment]
That part was brutally copy-pasted from another project where I used the random number to seed pseudo-random number generators (it's nice because Catch logs the seed when a test fails), which I don't use for `tight_pair`, so we can get rid of the `--rng-seed` part.

**Comment by Morwenn** [comment]
I've got a  bunch of small improvements that I can port from the other project, I might do that tonight. And I might create a dedicated Conan package, because why not.
